services:             
    tasklist-mysql:
        image: mysql:8.4
        container_name: tasklist-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'tasklist'
            MYSQL_USER: 'tasklist'
            MYSQL_PASSWORD: 'password'            
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3309:3306'
        expose:
            - '3306'
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
        networks:
            network:
                aliases:
                    - tasklist_mysql
    tasklist-sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: tasklist-sqlserver
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: '#sa#pw'                  
        ports:
            - '1439:1439'
        expose:
            - '1439'
        volumes:
            - tasklist-db:/var/lib/mssql            
            - ./WebContent/ddl:/scripts
        networks:
            network:
                aliases:
                    - tasklist_sqlserver
        command:                                            
            - /bin/bash
            - -c
            - |
               /opt/mssql/bin/sqlservr &
               pid=$$!
               echo "Waiting for MS SQL to be available"
               /opt/mssql-tools18/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$MSSQL_SA_PASSWORD -No -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
               is_up=$$? 
               while [ $$is_up -ne 0 ] ; do 
                 echo -e $$(date) 
                 /opt/mssql-tools18/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$MSSQL_SA_PASSWORD -No -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername" 
                 is_up=$$?
                 sleep 5 
               done
               for foo in /scripts/SQLServer*.ddl
                 do /opt/mssql-tools18/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -No -l 30 -e -i $$foo 
               done
               trap "kill -15 $$pid" SIGTERM
               wait $$pid
               exit 0  
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: tasklist-java
        depends_on:
            - tasklist-sqlserver
        container_name: tasklist-java
        volumes:
            - ./WebContent:/usr/local/tomcat/webapps/shop/
            - ./sample:/usr/local/tomcat/webapps/ROOT            
        networks:
            network:
                aliases:
                    - tasklist-java
        ports:
            - 80:8080
volumes: 
    tasklist-db:
    mysql-db:
networks:
    network:
