services:
    tasklist-mysql:
        image: mysql:8.4
        container_name: tasklist-mysql
        restart: always
        environment:
            MYSQL_DATABASE: "tasklist"
            MYSQL_USER: "tasklist"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - mysql-db:/var/lib/mysql
            - ./tasklistSQL/ddl:/docker-entrypoint-initdb.d
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "tasklist",
                    "-ppassword",
                ]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s

    backend:
        build: .
        container_name: hackathon-backend
        restart: always
        env_file: .env
        environment:
            MYSQL_HOST: tasklist-mysql
            MYSQL_PORT: "3306"
        ports:
            - "8000:8000"
        depends_on:
            tasklist-mysql:
                condition: service_healthy

    frontend:
        build:
            context: ../front-end
            args:
                VITE_API_BASE_URL: https://api.catasktrophy.talonl.ca
        container_name: hackathon-frontend
        restart: always
        ports:
            - "80:80"

volumes:
    mysql-db:
